---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
    level: warning
  trailing-spaces: enable
  truthy:
    allowed-values: ['true', 'false']
  comments:
    min-spaces-from-content: 1
  comments-indentation:
    level: warning
  document-start: disable
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1

ignore: |
  .github/
  templates/
