{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rustfs.fullname" . }}-credentials
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if or .Values.rootUser .Values.rootPassword }}
  {{/* Use configured credentials */}}
  RUSTFS_ACCESS_KEY: {{ .Values.rootUser | default "rustfsadmin" | b64enc | quote }}
  RUSTFS_SECRET_KEY: {{ .Values.rootPassword | default (randAlphaNum 20) | b64enc | quote }}
  {{- else }}
  {{/* Auto-generate default credentials when none specified */}}
  RUSTFS_ACCESS_KEY: {{ "rustfsadmin" | b64enc | quote }}
  RUSTFS_SECRET_KEY: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
{{- end }}
