{{- if not .Values.existingSecret }}
{{- $secretName := printf "%s-credentials" (include "rustfs.fullname" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}

{{/* Determine username */}}
{{- $username := .Values.rootUser | default "rustfsadmin" }}

{{/* Determine password based on priority: explicit > existing > generated */}}
{{- $password := "" }}
{{- if .Values.rootPassword }}
  {{/* Priority 1: Explicitly configured password */}}
  {{- $password = .Values.rootPassword }}
{{- else if $existingSecret }}
  {{/* Priority 2: Preserve existing password if compatible */}}
  {{- $existingUser := index $existingSecret.data "RUSTFS_ACCESS_KEY" | b64dec }}
  {{- if or (eq $username $existingUser) (eq $existingUser "rustfsadmin") }}
    {{/* Compatible: same user or upgrading from default */}}
    {{- $password = index $existingSecret.data "RUSTFS_SECRET_KEY" | b64dec }}
  {{- else }}
    {{/* Incompatible: different user, generate new password */}}
    {{- $password = randAlphaNum 20 }}
  {{- end }}
{{- else }}
  {{/* Priority 3: Generate new password for new deployments */}}
  {{- $password = randAlphaNum 20 }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
type: Opaque
data:
  RUSTFS_ACCESS_KEY: {{ $username | b64enc | quote }}
  RUSTFS_SECRET_KEY: {{ $password | b64enc | quote }}
{{- end }}
